[project]
name = "eui48-bit-distance"
version = "0.1.1rc1"
description = "Calculate bit distance between EUI-48 (MAC)."
authors = [
    {name = "Anton Shestakov", email = "av6@dwimlabs.net"}
]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries",
]

[project.urls]
"Homepage" = "https://github.com/antonv6/eui48-bit-distance"
"Source" = "https://github.com/antonv6/eui48-bit-distance"
"Issues" = "https://github.com/antonv6/eui48-bit-distance/issues"

[build-system]
requires = ["setuptools >= 78.1.1"]
build-backend = "setuptools.build_meta"

[dependency-groups]
test = [
    "pytest (>=9.1.1,<10.0.0)",
]
build = [
    "build",
    "twine",
]
dev = [
    {include-group = "test"},
    {include-group = "build"},
]

[pytest]
addopts = ["--import-mode=importlib"]
strict = true
