[project]
name = "eui48-bit-distance"
version = "0.2.5"
description = "Calculate bit distance between EUI-48 (MAC)."
authors = [
    {name = "Anton Shestakov", email = "av6@dwimlabs.net"}
]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries",
    "Typing :: Typed",
]

[project.urls]
"Source" = "https://github.com/antonv6/eui48-bit-distance"
"Issues" = "https://github.com/antonv6/eui48-bit-distance/issues"
"Changelog" = "https://github.com/antonv6/eui48-bit-distance/blob/main/CHANGELOG.md"
"Download" = "https://github.com/antonv6/eui48-bit-distance/releases"
"Docs" = "https://antonv6.github.io/eui48-bit-distance/"

[build-system]
requires = ["setuptools >= 78.1.1"]
build-backend = "setuptools.build_meta"

[dependency-groups]
doc = [
    "sphinx (>=9.1.0,<10.0.0)",
    "furo (==2025.12.19)",
]
lint = [
    "bandit (>=1.9.4,<2.0.0)",
    "flake8 (>=7.3.0,<8.0.0)",
    "flake8-bugbear (>=25.11.29,<26.0.0)",
    "flake8-commas (>=4.0.0,<5.0.0)",
    "flake8-pytest-style (>=2.2.0,<3.0.0)",
    "mypy (>=2.2.0,<3.0.0)",
    "pylint (>=4.0.6,<5.0.0)",
]
test = [
    "hypothesis (>=6.155.7,<7.0.0); implementation_name != 'pypy' or python_version >= '3.11'",
    "hypothesis (>=6.155.7,<6.156.0); implementation_name == 'pypy' and python_version < '3.11'",
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-benchmark (>=5.2.3,<6.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
]
build = [
    "build",
    "twine",
]
dev = [
    "tox (>=4.56.4,<5.0.0)",
    {include-group = "doc"},
    {include-group = "lint"},
    {include-group = "test"},
    {include-group = "build"},
]

[tool.pytest]
filterwarnings = ["error"]
strict = true

[tool.tox]
env_list = [
    "lint",
]

[tool.tox.env.lint]
dependency_groups = ["lint"]
skip_install = true
commands = [
    ["mypy", "--install-types", "--non-interactive"],
    ["bandit", "-r", "docs", "src"],
    ["flake8", "docs", "src", "tests"],
    ["pylint", "src"],
]

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
fail_under = 100
show_missing = true

[tool.mypy]
explicit_package_bases = true
files = [
    "docs",
    "src",
    "tests",
]
strict = true

[[tool.mypy.overrides]]
module = ["tests.*"]
disallow_untyped_defs = false

[[tool.mypy.overrides]]
module = [
    "hypothesis",
    "pytest",
]
ignore_missing_imports = true

[tool.pylint.main]
ignore-paths = [
    "^docs/",
    "^tests/",
]

[tool.pylint.format]
max-line-length = 120
